In [1]:
import numpy as np
x = np.array([[1,2,3],[1,2,3]])
y = np.random.randint(0,10,size=(3,5))
print(x)
print(y)
print(np.dot(x,y))


[[1 2 3]
 [1 2 3]]
[[4 1 4 9 1]
 [3 4 2 9 1]
 [3 9 6 1 8]]
[[19 36 26 30 27]
 [19 36 26 30 27]]


In [3]:
hidSize = 10
inputSize = 4
w1 = np.random.normal(0.0, pow(hidSize, -0.5), (hidSize, inputSize))   # 权重
print(w1)

[[-0.25838797  0.26519444 -0.42793527 -0.12861945]
 [ 0.30073671 -0.53271873 -0.13115115 -0.02476741]
 [ 0.10065121  0.27817451  0.33222777  0.04257687]
 [ 0.41022211  0.14163236 -0.36807594 -0.61403762]
 [ 0.16596794 -0.51809979  0.43003177  0.24531226]
 [-0.11162053 -0.46318745 -0.21122916  0.27044822]
 [ 0.00319097 -0.32604984  0.20101165 -0.12103691]
 [-0.38194138  0.05841849 -0.29325826  0.12762714]
 [ 0.03853893  0.18227592 -0.27359711  0.23361881]
 [ 0.13346041 -0.17117535 -0.34357708 -0.38170151]]
